### ISSUE TITLE
Unable to switch from infraonly to fullstack monitoring

### ISSUE THREAD

**Issue by vipinvkmenon** [Dynatrace/bosh-oneagent-release#58] opened 2020-12-18 13:37 UTC
As we were working on bringing `infraonly` flag for a bosh deployment we came across a quirk.

When we enable `infraonly` mode and try to switch it back to full-stack the bosh agent is not willing to do it. Is this the intended behaviour?
Switching from `full-stack` to `infraonly` works. However, it cannot switch back to `full-stack` mode gain. It seems like this switch can happen only when the bosh VM is recreated.

On trying to understand what is going on we did an analysis and came across a few observations:

![image](https://user-images.githubusercontent.com/3639797/102618624-23038b00-4161-11eb-9c0c-7589d53152b0.png)

1. We can see that there are some configurations that are set in /var/lib (Questionable choice of location in cloud environments IMHO…)
2. There is a configuration file `infraonly.conf` which gets initialized when the flag is enabled.
3. This file once configured does not seem to get reset. (as can be seen from the date)

We tried using both the flags: `infraonly` and `INSTALLERARGS: INFRA_ONLY=1`

What we noticed that within the installer file located `/var/vcap/packages/Dynatrace-OneAgent-Linux-x.xxx.sh` file there was a logic that sets this file and it seemed to be a onetime initialisation activity.

![image](https://user-images.githubusercontent.com/3639797/102619976-4b8c8480-4163-11eb-9a69-e38699ba08ce.png)

The next time the agent would reset, only when the VM  is recreated. (I.E when the config files are no longer present in the /var/lib location)

This makes it difficult to use it in production environments when we need to make switches.

**Comment by arthfl** [comment] 2021-01-04 10:35
Have you tried setting the parameter to false or 0 (depending on which you use)?
That should do the job as a workaround.

**Comment by vipinvkmenon** [comment] 2021-01-07 10:49
Hi as with the documentation, we tried setting it to 0. However, the agent still reports as infraonly mode in DT.
I also tried setting infraonly to false. However, this also did not work.

**Comment by arthfl** [comment] 2021-01-20 11:20
Sorry for the late answer. Vacations happen ;-)

We'll try to reproduce this and get back to you.

**Comment by arthfl** [comment] 2021-01-22 11:11
@vipinvkmenon i was only partially able to reproduce this.
When using the `infraonly: 0` property setting it indeed doesn't get reverted to full-stack monitoring.
But when i used `installerargs: INFRA_ONLY=0` it worked just fine and as expected.

Which version of the bosh-release where you using and did you try this exact approach?

**Comment by arthfl** [comment] 2021-01-26 11:48
I'm closing this, since it's solveable with using the `installerargs` property in the runtime-config

**Closed by arthfl** 2021-01-26 11:48 UTC
