### ISSUE TITLE
[Release 1.3.3] Proxy configuration 

### ISSUE THREAD

**Issue by giva01121** [Dynatrace/bosh-oneagent-release#57] opened 2020-10-29 11:17 UTC
Hello,
after updating the release version from 1.3.2 to 1.3.3, our proxy setup stopped working. Once the version was reverted to 1.3.2 the issue was fixed.
```
 sha1: fd97b6068e76e5b3265b9cfd5a121e6a7bb26a37
  url: https://bosh.io/d/github.com/Dynatrace/bosh-oneagent-release?v=1.3.3
  version: 1.3.3
```
We saw the following error in the install log:
```
11:04:18 Dynatrace OneAgent failed to connect to Dynatrace Cluster Node https://dynatrace.random:8443/communication. See log file for details: /var/vcap/data/dynatrace/oneagent/log/os/ruxitagent_host_14851.0.log Installation finished
```
And this is ruxitagent_host_14851.0.log 
```
2020-10-28 11:10:29.182 UTC [e88dd8c8] info    [native] Storage path ................ /var/vcap/data/dynatrace/oneagent
2020-10-28 11:10:29.182 UTC [e88dd8c8] info    [native] Tenant UUID ................. 02ed582b-10d4-4dde-895b-98f18918cdbe
2020-10-28 11:10:29.182 UTC [e88dd8c8] info    [native] Tenant ID ................... 0xcc09a1cd
2020-10-28 11:10:29.182 UTC [e88dd8c8] info    [native] Network zone ................
2020-10-28 11:10:29.182 UTC [e88dd8c8] info    [native] Agent ID .................... 0x31dcd25339b2cbb1
2020-10-28 11:10:29.182 UTC [e88dd8c8] info    [native] Process group ID ............ 0x2e81c7cd12261c61
2020-10-28 11:10:29.183 UTC [e88dd8c8] info    [native] OSI ID ...................... 0x99ae3242cb44636d
2020-10-28 11:10:29.183 UTC [e88dd8c8] info    [native] Node ID ..................... 0x0000000000000000
2020-10-28 11:10:29.183 UTC [e88dd8c8] info    [native] Process group instance ID ... 0xb8cbc19f0dba6303
2020-10-28 11:10:29.183 UTC [e88dd8c8] info    [native] Container group ID .......... 0x0000000000000000
2020-10-28 11:10:29.183 UTC [e88dd8c8] info    [native] Container group instance ID . 0x0000000000000000
2020-10-28 11:10:29.183 UTC [e88dd8c8] info    [native] Container ID ................
2020-10-28 11:10:29.183 UTC [e88dd8c8] info    [native] Agent host .................. 2d2397f0-d596-42ed-a12c-470efb4cd0bf
2020-10-28 11:10:29.183 UTC [e88dd8c8] info    [native] Injection mode .............. UNKNOWN
2020-10-28 11:10:29.183 UTC [e88dd8c8] info    [native] Standalone .................. no
2020-10-28 11:10:29.183 UTC [e88dd8c8] info    [native] Log file aging .............. disabled
2020-10-28 11:10:29.183 UTC [e88dd8c8] info    [native] Agent name .................. host
2020-10-28 11:10:29.183 UTC [e88dd8c8] info    [native] Server/Collector ............ https://dynatrace.random:8443/communication;https://cluster-activegate.dynatrace.random:9999/communication
2020-10-28 11:10:29.183 UTC [e88dd8c8] info    [native] Proxy .......................
2020-10-28 11:10:29.183 UTC [e88dd8c8] info    [native] Dispatcher buffersize ....... 419430400
```

**Comment by arthfl** [comment] 2020-11-02 13:15
Can you share an exemplary runtime-config which reflects your configuration?
So we can try to reproduce this properly on our end.

**Comment by akop** [comment] 2020-11-03 07:26
Hi,

thanks for your reply. We have the following setting in runtime-config which is working with 1.3.2 when we switch to 1.3.3 the agent download is working with proxy but it seems the agent is not using the proxy to deliver the data to dynatrace. The agent is asking the local DNS server instead of using the configured proxy to reach the remote dynatrace server.

```
- name: dynatrace-oneagent-addon
  jobs:
  - name: dynatrace-oneagent
    release: dynatrace-oneagent
  include:
    deployments:
    - cf
    stemcell:
    - os: ubuntu-xenial
  exclude:
    lifecycle: errand
  properties:
    dynatrace:
      environmentid: "((iaas.dynatrace.environmentid))"
      apitoken: "((/dynatrace_oneagent_apitoken))"
      apiurl: https://((iaas.dynatrace.apihost))/e/((iaas.dynatrace.environmentid))/api
      hostgroup: "((iaas.cf.system_domain))"
      infraonly: 0
      validatedownload: false
      proxy: "((http_proxy))"
```

**Comment by arthfl** [comment] 2020-11-03 10:35
Thanks, i'll try to reproduce this.

Could you, in the meantime, also share the install log of the bosh-release from `/var/vcap/sys/log/dynatrace-oneagent/dynatrace-install.log`? Make sure to remove any sensitive data from it though :-)

**Comment by giva01121** [comment] 2020-11-03 13:50
> Thanks, i'll try to reproduce this.
> 
> Could you, in the meantime, also share the install log of the bosh-release from `/var/vcap/sys/log/dynatrace-oneagent/dynatrace-install.log`? Make sure to remove any sensitive data from it though :-)
Hi, thanks for the support here's the install log:
[Dynatrace_install.log](https://github.com/Dynatrace/bosh-oneagent-release/files/5481573/Dynatrace_install.log)

**Comment by arthfl** [comment] 2020-11-04 09:59
I did some quick tests with v1.3.2 and v1.3.3 and got the same result for both. Which is kinda what i expected, since the logic at that place didn't change between the two versions. Just some variables got renamed.
And for downloading the agent the proxy settings seemed to have worked fine, because otherwords you'd have gotten some errors like this:
```bash
Downloading agent installer from <TENANT>
curl: (5) Could not resolve proxy: <NONFUNCTIONALPROXY>
```

So the problem is possibly not with the bosh-release itself but somewhere else. Do you know if the same installer/agent version was used in both cases? In the attached install log it was `1.201.129.20201001-102441`.

**Comment by giva01121** [comment] 2020-11-04 10:54
@arthfl thanks for the effort, I can see that for both versions, the installer is `1.201.129.20201001-102441`
what does it mean this?

**Comment by arthfl** [comment] 2020-11-05 12:05
@giva01121 Since this doesn't look like an issue with the bosh-release itself but maybe rather with the installer (which is fetched by the release), can you open a support case with us (Dynatrace) for this please?

I'm closing this issue with that, since the follow-up will be handled internally :-)

**Closed by arthfl** 2020-11-05 12:05 UTC
